create EXTENSION hstore;
create EXTENSION plperl;
create EXTENSION hstore_plperl;
create EXTENSION jsonb_plperl;
create EXTENSION plperlu;
create EXTENSION jsonb_plperlu;
create EXTENSION pg_freespacemap;
create EXTENSION pg_partman;
create EXTENSION tdigest;
create EXTENSION mysql_fdw;
-- create EXTENSION pg_cron;
