apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: healthcheck-pv-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
status: {}
