apiVersion: v1
kind: PersistentVolume
metadata:
  name: citus-mgr-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /opt/data/citus/manager
