apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: manager-pv-claim0-volume
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
