apiVersion: apps/v1
kind: Deployment
metadata:
  name: citus-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: citus-manager
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: citus-manager
    spec:
      serviceAccountName: pod-listing-sa
      containers:
        - env:
            - name: NAMESPACE
              value: integration-test
            - name: MASTER_SERVICE
              value: pg-citus-master
            - name: PGPASSWORD
            - name: PGUSER
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: postgres
          image: bakdata/citus-k8s-membership-manager:v0.3
          name: citus-manager-container
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          volumeMounts:
            - name: citus-config-mount
              mountPath: /etc/citus-config
      restartPolicy: Always
      volumes:
        - name: citus-config-mount
          configMap:
            name: setup-config
status: {}
