apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pg-citus-master
spec:
  serviceName: "pg-citus-master"
  replicas: 1
  selector:
    matchLabels:
      app: citus-master
  template:
    metadata:
      labels:
        app: citus-master
        citusType: "citus-master"
    spec:
      serviceAccountName: pod-listing-sa
      subdomain: pg-citus-master
      containers:
        - env:
            - name: PGPASSWORD
            - name: PGUSER
              value: postgres
            - name: POSTGRES_HOST_AUTH_METHOD
              value: trust
            - name: POSTGRES_PASSWORD
            - name: POSTGRES_USER
              value: postgres
          image: citusdata/citus:10.2.3
          name: citus-master
          ports:
            - containerPort: 5432
          resources: {}
      restartPolicy: Always
