apiVersion: v1
kind: Service
metadata:
  name: pg-citus-master
  labels:
    app: citus-master
spec:
  ports:
    - name: "psql"
      port: 5432
      targetPort: 5432
  selector:
    app: citus-master
status:
  loadBalancer: {}
