apiVersion: v1
kind: Service
metadata:
  name: pg-citus-worker
  labels:
    app: citus-worker
spec:
  ports:
    - name: "psql"
      port: 5432
      targetPort: 5432
  selector:
    app: citus-worker
status:
  loadBalancer: {}
